# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: pdk的日常记录
email: 19921207pq@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pengdake.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
github_username:  pengdake

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-include-cache

collections: []

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

permalink: /:year/:month/:day/:title/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

lang: zh-CN
navigation:
  enabled: true
  data: navigation
